spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  retry:
    initial-delay: 1000
    max-delay: 10000
    max-attempts: 3
    multiplier: 2

  sql:
    init:
      mode: always
      schema-locations: classpath:db/changelog/init.sql

server:
  port: 8080

logging:
  level:
    root: info